import React from "react";
import { Column, InputTableDataItem } from "../../Types/Types";
import { customStyleClasses } from "@cg-components/BasicTable/Types/Types";
type Props = {
    columns: Column[];
    displayData: InputTableDataItem[];
    withActionColumn?: boolean;
    disabled: boolean;
    isValidSaveCallback?: (newItem: InputTableDataItem) => boolean | Promise<boolean>;
    onCancelHandler: (rowIndex: number) => void;
    onEditHandler: (rowIndex: number) => void;
    onRemoveHandler: (rowIndex: number) => void;
    onChangeCellHandler: (value: string | boolean | number, rowIndex: number, field: string | number) => void;
    onSaveHandler: (rowIndex: number) => Promise<void>;
    activeIndex: number | null;
    hiddenIndexes: number[];
    withCellBackground?: boolean;
    isValidCellCallback?: (field: string, cellValue: string | number | boolean) => boolean | Promise<boolean>;
    onMouseEnterCallback?: (rowIndex: number, colIndex: number) => void;
    onMouseLeaveCallback?: (rowIndex: number, colIndex: number) => void;
    numberFormatCallBack?: (value: number | string, rowIndex: number, colIndex: number) => string;
    customStyle?: customStyleClasses;
};
export default function DesktopTableBody(props: Props): React.JSX.Element;
export {};
