import * as React from "react";
import type { StoryObj } from "@storybook/react";
declare const meta: {
    title: string;
    component: ({ handleSubmit, children, isValid, logo, formFooter, formHeader, ...props }: {
        textButton?: React.ReactNode;
        formHeader?: React.ReactNode;
        formFooter?: React.ReactNode;
        logo?: React.ReactNode;
        handleSubmit?: (e: React.FormEvent<HTMLFormElement> | React.KeyboardEvent<HTMLInputElement>, isValid?: boolean) => Promise<void>;
        isValid?: boolean;
        children?: React.ReactNode;
    } & React.ClassAttributes<HTMLFormElement> & React.FormHTMLAttributes<HTMLFormElement>) => React.JSX.Element;
    tags: string[];
    decorators: ((Story: import("@storybook/csf").PartialStoryFn<import("@storybook/react").ReactRenderer, {
        children?: React.ReactNode;
        formHeader?: React.ReactNode;
        formFooter?: React.ReactNode;
        className?: string | undefined;
        logo?: React.ReactNode;
        isValid?: boolean | undefined;
        handleSubmit?: ((e: React.FormEvent<HTMLFormElement> | React.KeyboardEvent<HTMLInputElement>, isValid?: boolean) => Promise<void>) | undefined;
        ref?: React.LegacyRef<HTMLFormElement> | undefined;
        key?: React.Key | null | undefined;
        acceptCharset?: string | undefined;
        action?: string | undefined | React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS[keyof React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS];
        autoComplete?: string | undefined;
        encType?: string | undefined;
        method?: string | undefined;
        name?: string | undefined;
        noValidate?: boolean | undefined;
        target?: string | undefined;
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: React.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: React.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCopyCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCut?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCutCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onPaste?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onPasteCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCompositionEnd?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionEndCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionStart?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionStartCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionUpdate?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onFocus?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onFocusCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onBlur?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onBlurCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onChange?: React.FormEventHandler<HTMLFormElement> | undefined;
        onChangeCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onBeforeInput?: React.FormEventHandler<HTMLFormElement> | undefined;
        onBeforeInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInput?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onReset?: React.FormEventHandler<HTMLFormElement> | undefined;
        onResetCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onSubmit?: React.FormEventHandler<HTMLFormElement> | undefined;
        onSubmitCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInvalid?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInvalidCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onLoad?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onError?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onErrorCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onKeyDown?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyDownCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyPress?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyPressCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyUp?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyUpCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onAbort?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onAbortCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayThrough?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayThroughCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onDurationChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onDurationChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEmptied?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEmptiedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEncrypted?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEncryptedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEnded?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEndedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedData?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedDataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedMetadata?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedMetadataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadStart?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadStartCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPause?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPauseCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlaying?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlayingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onProgress?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onProgressCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onRateChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onRateChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onResize?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onResizeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeeked?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeekedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeeking?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeekingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onStalled?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onStalledCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSuspend?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSuspendCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTimeUpdate?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTimeUpdateCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onVolumeChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onVolumeChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onWaiting?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onWaitingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onAuxClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onAuxClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onContextMenu?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onContextMenuCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDoubleClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDoubleClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDrag?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnd?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEndCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnter?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnterCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragExit?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragExitCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragLeave?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragLeaveCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragOver?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragOverCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragStart?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragStartCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDrop?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDropCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onMouseDown?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseDownCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseEnter?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseLeave?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseMove?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseMoveCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOut?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOutCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOver?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOverCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseUp?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseUpCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onSelect?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSelectCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTouchCancel?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchCancelCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchEnd?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchEndCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchMove?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchMoveCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchStart?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchStartCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onPointerDown?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerDownCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerMove?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerMoveCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerUp?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerUpCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerCancel?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerCancelCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerEnter?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerLeave?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOver?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOverCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOut?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOutCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onGotPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onLostPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onScroll?: React.UIEventHandler<HTMLFormElement> | undefined;
        onScrollCapture?: React.UIEventHandler<HTMLFormElement> | undefined;
        onWheel?: React.WheelEventHandler<HTMLFormElement> | undefined;
        onWheelCapture?: React.WheelEventHandler<HTMLFormElement> | undefined;
        onAnimationStart?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationStartCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationEnd?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationEndCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationIteration?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationIterationCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onTransitionEnd?: React.TransitionEventHandler<HTMLFormElement> | undefined;
        onTransitionEndCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    }>, props: import("@storybook/csf").StoryContext<import("@storybook/react").ReactRenderer, {
        children?: React.ReactNode;
        formHeader?: React.ReactNode;
        formFooter?: React.ReactNode;
        className?: string | undefined;
        logo?: React.ReactNode;
        isValid?: boolean | undefined;
        handleSubmit?: ((e: React.FormEvent<HTMLFormElement> | React.KeyboardEvent<HTMLInputElement>, isValid?: boolean) => Promise<void>) | undefined;
        ref?: React.LegacyRef<HTMLFormElement> | undefined;
        key?: React.Key | null | undefined;
        acceptCharset?: string | undefined;
        action?: string | undefined | React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS[keyof React.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS];
        autoComplete?: string | undefined;
        encType?: string | undefined;
        method?: string | undefined;
        name?: string | undefined;
        noValidate?: boolean | undefined;
        target?: string | undefined;
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: React.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: React.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCopyCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCut?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCutCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onPaste?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onPasteCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
        onCompositionEnd?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionEndCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionStart?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionStartCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionUpdate?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
        onFocus?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onFocusCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onBlur?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onBlurCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
        onChange?: React.FormEventHandler<HTMLFormElement> | undefined;
        onChangeCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onBeforeInput?: React.FormEventHandler<HTMLFormElement> | undefined;
        onBeforeInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInput?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onReset?: React.FormEventHandler<HTMLFormElement> | undefined;
        onResetCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onSubmit?: React.FormEventHandler<HTMLFormElement> | undefined;
        onSubmitCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInvalid?: React.FormEventHandler<HTMLFormElement> | undefined;
        onInvalidCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
        onLoad?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onError?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onErrorCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onKeyDown?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyDownCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyPress?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyPressCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyUp?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onKeyUpCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
        onAbort?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onAbortCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayThrough?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onCanPlayThroughCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onDurationChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onDurationChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEmptied?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEmptiedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEncrypted?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEncryptedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEnded?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onEndedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedData?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedDataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedMetadata?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadedMetadataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadStart?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onLoadStartCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPause?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPauseCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlaying?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onPlayingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onProgress?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onProgressCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onRateChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onRateChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onResize?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onResizeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeeked?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeekedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeeking?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSeekingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onStalled?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onStalledCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSuspend?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSuspendCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTimeUpdate?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTimeUpdateCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onVolumeChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onVolumeChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onWaiting?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onWaitingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onAuxClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onAuxClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onContextMenu?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onContextMenuCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDoubleClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDoubleClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onDrag?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnd?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEndCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnter?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragEnterCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragExit?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragExitCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragLeave?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragLeaveCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragOver?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragOverCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragStart?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDragStartCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDrop?: React.DragEventHandler<HTMLFormElement> | undefined;
        onDropCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
        onMouseDown?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseDownCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseEnter?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseLeave?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseMove?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseMoveCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOut?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOutCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOver?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseOverCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseUp?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onMouseUpCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
        onSelect?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onSelectCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
        onTouchCancel?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchCancelCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchEnd?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchEndCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchMove?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchMoveCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchStart?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onTouchStartCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
        onPointerDown?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerDownCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerMove?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerMoveCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerUp?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerUpCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerCancel?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerCancelCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerEnter?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerLeave?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOver?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOverCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOut?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onPointerOutCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onGotPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onLostPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
        onScroll?: React.UIEventHandler<HTMLFormElement> | undefined;
        onScrollCapture?: React.UIEventHandler<HTMLFormElement> | undefined;
        onWheel?: React.WheelEventHandler<HTMLFormElement> | undefined;
        onWheelCapture?: React.WheelEventHandler<HTMLFormElement> | undefined;
        onAnimationStart?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationStartCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationEnd?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationEndCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationIteration?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onAnimationIterationCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
        onTransitionEnd?: React.TransitionEventHandler<HTMLFormElement> | undefined;
        onTransitionEndCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    }>) => React.JSX.Element)[];
    args: {
        children: React.JSX.Element;
    };
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const DefaultLoginForm: Story;
