import React from "react";
import { customStyleClasses, ListItem, Position } from "../Types/types";
type DraggedContextValue = {
    listItems: ListItem[];
    setListItems: React.Dispatch<React.SetStateAction<ListItem[]>>;
    moveToTopButton?: React.ReactNode;
    moveToBottomButton?: React.ReactNode;
    dragIcon?: React.ReactNode;
    customStyle?: customStyleClasses;
    onChangeSortingOrder: (list: ListItem[]) => void;
    initialDraggingItemPosition: Position | null;
    draggedListItemRef: React.MutableRefObject<HTMLElement | undefined> | undefined;
    setInitialStateForListItem: () => void;
    setMousePosition: React.Dispatch<React.SetStateAction<Position | null>>;
    initialMousePosition: Position | null;
    setNewSortingOrder: () => void;
    movingToIndex: number | null;
    customClassForListItem?: string;
    setMovingToIndex: React.Dispatch<React.SetStateAction<number | null>>;
    mousePosition: Position | null;
    setInitialMousePosition: React.Dispatch<React.SetStateAction<Position | null>>;
    setInitialDraggingItemPosition: React.Dispatch<React.SetStateAction<Position | null>>;
    setDraggingIndex: React.Dispatch<React.SetStateAction<number | null>>;
    draggingIndex: number | null;
    highlightedIndex: number | null;
    setDraggedListItemRef: React.Dispatch<React.SetStateAction<React.MutableRefObject<HTMLElement | undefined> | undefined>>;
    moveItemToTop: (itemToMoveIndex: number) => void;
    moveItemToBottom: (itemToMoveIndex: number) => void;
    setHighlightedIndex: React.Dispatch<React.SetStateAction<number | null>>;
};
export declare const DraggedContext: React.Context<DraggedContextValue>;
type Props = {
    children: React.ReactNode;
    list: ListItem[];
    moveToTopButton?: React.ReactNode;
    moveToBottomButton?: React.ReactNode;
    dragIcon?: React.ReactNode;
    customStyle?: customStyleClasses;
    onChangeSortingOrder: (list: ListItem[]) => void;
};
declare const DraggedContextProvider: ({ list, moveToTopButton, moveToBottomButton, dragIcon, customStyle, onChangeSortingOrder, children }: Props) => React.JSX.Element;
export default DraggedContextProvider;
